# fly.toml app configuration file generated for pkce-proxy on 2024-01-06T12:49:43+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "raycast-pkce-proxy-splitwise"
primary_region = "lhr"

[build]

[build.http_service]
internal_port = 5000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[build.vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
